name: pulsar-detector
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyter
  - ipykernel
  - joblib
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - pydantic
      - pytest
      - imbalanced-learn
      - xgboost
      - catboost
      - -e .